### ISSUE TITLE
Subscriptions do not cleanup

### ISSUE THREAD

**Issue by spencekim** [jsonnull/electron-trpc#124]
Using your example repo, I noticed that subscriptions do not clean up. Eventually I get the following error:

```
[1] (node:22811) MaxListenersExceededWarning: Possible EventEmitter memory leak detected. 11 output listeners added to [EventEmitter]. Use emitter.setMaxListeners() to increase limit
[1] (Use `Electron --trace-warnings ...` to show where the warning was created)
[1] (node:22811) MaxListenersExceededWarning: Possible EventEmitter memory leak detected. 11 destroyed listeners added to [EventEmitter]. Use emitter.setMaxListeners() to increase limit
[1] subscribed
```

**Comment by spencekim** [comment]
In `/electon/api.ts`, if you console.log in the cleanup function within the observable, you will see that the component unmounts without cleaning up.

**Comment by jsonnull** [comment]
Hi, thanks for reporting the issue! I'll take a look at this and see what's happening.

**Comment by spencekim** [comment]
were you able to confirm this behavior?

**Comment by biw** [comment]
It looks like the return value in the subscription `observable` never get's called. Can reproduce it in the [`example/basic-react`](https://github.com/jsonnull/electron-trpc/blob/main/examples/basic-react/electron/api.ts#L27-L29) folder:

```ts
  return () => {
        ee.off('greeting', onGreet);
        console.log('removed event onGreen ');
      };
```

The function is only fired once the electron app closes, rather than when the component that uses the `useSubscription` function is unmounted. Currently looking into the code to find out more if you have any ideas @jsonnull, I will make a PR with the changes once I find it.

**Comment by jsonnull** [comment]
So I looked into this and I've found a pretty big oversight in the subscription architecture on the server-side. There's multiple issues here that were converging.

As Ben's pointed out (thanks for making this part easy!) the `subscription.stop` message is sent to the server, but the server isn't set up to handle this correctly.

It turns out that there's more than that. As Ben also points out, each new subscription was setting a handler on the window to clean up the subscription when the window is destroyed. This is the leak. What's worse is, since the `subscription.stop` method wasn't being handled, not only was the subscription not getting cleaned up, but this listener on the window's EventEmitter wasn't getting cleaned up either.

I've got a fix working where the subscription cleanup runs, and there's only one listener per window for the window destruction no matter how many subscriptions run.

So I just need to clean up that fix, check on tests, and I'll push the fix out.

**Comment by spencekim** [comment]
Very glad you found the issue. I'll give it a test once it's merged in, hopefully soon!

**Comment by jsonnull** [comment]
Alright, `electron-trpc@0.5.0` is out with a fix. If you get a chance, let me know if things are working better for you!

**Comment by spencekim** [comment]
Confirming that it works! Thanks!
